### ISSUE TITLE
Cannot compile :(

### ISSUE THREAD

**Issue by murriiot** [mmolimar/ksql-jdbc-driver#21]
Is this due to the java version?

`[error] sbt.librarymanagement.ResolveException: Error downloading org.openjfx:javafx.base:11.0.0-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /Users/joel/.ivy2/local/org.openjfx/javafx.base/11.0.0-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/openjfx/javafx.base/11.0.0-SNAPSHOT/javafx.base-11.0.0-SNAPSHOT.pom
[error]   not found: https://packages.confluent.io/maven/org/openjfx/javafx.base/11.0.0-SNAPSHOT/javafx.base-11.0.0-SNAPSHOT.pom
[error]   not found: https://s3-us-west-2.amazonaws.com/confluent-snapshots/org/openjfx/javafx.base/11.0.0-SNAPSHOT/javafx.base-11.0.0-SNAPSHOT.pom
[error]   not found: /Users/joel/.m2/repository/org/openjfx/javafx.base/11.0.0-SNAPSHOT/javafx.base-11.0.0-SNAPSHOT.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:245)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$34(CoursierDependencyResolution.scala:214)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:214)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:52)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:102)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:115)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:115)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:96)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:129)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2947)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:835)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.openjfx:javafx.base:11.0.0-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /Users/joel/.ivy2/local/org.openjfx/javafx.base/11.0.0-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/openjfx/javafx.base/11.0.0-SNAPSHOT/javafx.base-11.0.0-SNAPSHOT.pom
[error]   not found: https://packages.confluent.io/maven/org/openjfx/javafx.base/11.0.0-SNAPSHOT/javafx.base-11.0.0-SNAPSHOT.pom
[error]   not found: https://s3-us-west-2.amazonaws.com/confluent-snapshots/org/openjfx/javafx.base/11.0.0-SNAPSHOT/javafx.base-11.0.0-SNAPSHOT.pom
[error]   not found: /Users/joel/.m2/repository/org/openjfx/javafx.base/11.0.0-SNAPSHOT/javafx.base-11.0.0-SNAPSHOT.pom
[error] Total time: 7 s, completed 14 de març 2020, 11:19:21`

**Comment by Liorba** [comment]
same for me :(
any updates?

**Comment by mmolimar** [comment]
Which Java version are you using?

**Comment by jaceksan** [comment]
Same for me:
```
jacek@holly:~/work/src/other/ksql-jdbc-driver$ java -version
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```

Fails with:
```
[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading org.openjfx:javafx.base:11.0.0-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /home/jacek/.ivy2/local/org.openjfx/javafx.base/11.0.0-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/openjfx/javafx.base/11.0.0-SNAPSHOT/javafx.base-11.0.0-SNAPSHOT.pom
[error]   not found: https://packages.confluent.io/maven/org/openjfx/javafx.base/11.0.0-SNAPSHOT/javafx.base-11.0.0-SNAPSHOT.pom
[error]   not found: https://s3-us-west-2.amazonaws.com/confluent-snapshots/org/openjfx/javafx.base/11.0.0-SNAPSHOT/javafx.base-11.0.0-SNAPSHOT.pom
[error]   not found: /home/jacek/.m2/repository/org/openjfx/javafx.base/11.0.0-SNAPSHOT/javafx.base-11.0.0-SNAPSHOT.pom
```

**Comment by mmolimar** [comment]
Hi.
Try with JDK8, please

**Comment by jaceksan** [comment]
Hi,
unfortunately jdk8 is no longer an option in our environments.
Do you plan to add support for jdk11?

**Comment by mmolimar** [comment]
Yes, that's one of the new things I want to include in the next release ;-)

**Comment by jaceksan** [comment]
Cool, so I wait for it.
Another option is that KSQLDB devs will do it, I asked them in their slack and they plan to do it, 
just ETA is unknown, so it may take long time.
That is why I really appreciate your work here ;-)
